name: alquranapp
version: 1.0.0+1
publish_to: none
description: Flutter Islamic App Project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^4.0.0
  iconsax: ^0.0.8
  flutter_custom_clippers: ^2.1.0
  flutter_svg: ^1.1.6
  skeletons: ^0.0.3
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_gauges: ^20.4.44
  intl:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21